spring:
  plataform: mariadb
  driveClasseName: org.mariadb.jdbc.Drive
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mariadb://localhost:3306/fornecedor
    username: root
    password: root